version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: 'mariadb'
    restart: always
    environment:
      MYSQL_DATABASE: hetic_wordpress
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./hetic_wordpress.sql:/docker-entrypoint-initdb.d/hetic_wordpress.sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1